kl/search/urls.py
from django.conf.urls import url

from kl.search import views


app_name = 'search'

urlpatterns = [
    url(
        r'^$',
        views.home,
        name='home'
    ),
    url(
        r'^json/$',
        views.home,
        {'json': True},
        name='home',
    ),
    url(
        r'^searches/(?P<year>\d{4})/(?P<month>\w+)/$',
        views.searches_summary,
        name='searches_summary'
    ),
    url(
        r'^about/crosstips/$',
        views.about_crosstips,
        name='about_crosstips'
    ),

]

kl/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static



urlpatterns = [
    url(
        '',
        include('kl.search.urls', namespace='search')
    ),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

kl/search/models.py
from django.db import models


class Word(models.Model):
    """
    A Word has two important parts: the word, its length
    and there's also the optional part_of_speech. The length always
    has to be that of the word:

        >>> w = Word.objects.create(word=u'Peter',
        ...                         part_of_speech=u'egenamn',
        ...                         language='sv')
        >>> w.length == len(u'Peter')
        True

    """
    class Meta:
        db_table = 'words'

    word = models.CharField(max_length=40)
    language = models.CharField(max_length=5)
    length = models.IntegerField()
    part_of_speech = models.CharField(max_length=20, null=True)
    definition = models.CharField(max_length=250, null=True)
    name = models.BooleanField()
    # used for optimization
    first1 = models.CharField(max_length=1)
    first2 = models.CharField(max_length=2)
    last1 = models.CharField(max_length=1)
    last2 = models.CharField(max_length=2)

    def __str__(self):
        return self.word

    def __repr__(self):
        return '<{} {!r} ({})>'.format(
            self.__class__.__name__,
            self.word,
            self.language
        )

    def __init__(self, *args, **kwargs):
        if 'word' in kwargs:
            if 'length' in kwargs:
                assert kwargs['length'] == len(kwargs['word'])
            else:
                kwargs['length'] = len(kwargs['word'])

            if 'first1' in kwargs:
                try:
                    assert kwargs['first1'] == kwargs['word'][0].lower()
                except AssertionError:
                    kwargs['first1'] = kwargs['word'][0].lower()
                    # print((kwargs['first1'], kwargs['word']))
                    # raise
            else:
                kwargs['first1'] = kwargs['word'][0].lower()
            if 'first2' in kwargs:
                try:
                    assert kwargs['first2'] == kwargs['word'][:2].lower()
                except AssertionError:
                    kwargs['first2'] = kwargs['word'][:2].lower()
                    # print((kwargs['first2'], kwargs['word']))
                    # raise
            else:
                kwargs['first2'] = kwargs['word'][:2].lower()

            if 'last1' in kwargs:
                assert kwargs['last1'] == kwargs['word'][-1].lower()
            else:
                kwargs['last1'] = kwargs['word'][-1].lower()
            if 'last2' in kwargs:
                assert kwargs['last2'] == kwargs['word'][-2:].lower()
            else:
                kwargs['last2'] = kwargs['word'][-2:].lower()

        super(Word, self).__init__(*args, **kwargs)


class Search(models.Model):
    """ A search is a record of someone doing a search.
    """

    class Meta:
        db_table = 'searches'
        verbose_name_plural = 'Searches'

    search_word = models.CharField(max_length=40)
    add_date = models.DateTimeField('date added', auto_now_add=True,
                                    db_index=True)
    user_agent =  models.CharField(max_length=200, default='')
    ip_address =  models.CharField(max_length=15, default='')
    language = models.CharField(max_length=5, default='')
    search_type = models.CharField(max_length=50, default='')

    found_word = models.ForeignKey(Word, null=True, blank=True,
        on_delete=models.deletion.CASCADE)

    def __str__(self):
        return self.search_word

kl/search/views.py
import datetime
import re
from random import shuffle
from collections import defaultdict

from django.utils.translation import (
    activate,
    get_language_info,
    get_language,
)
from django import http
from django.shortcuts import render
from django.core.cache import cache
from django.conf import settings
from django.utils.translation import get_language
from django.utils.translation import ugettext as _
from django.utils import timezone

try:
    from nltk.corpus import wordnet
except ImportError:
    wordnet = None


from kl.search.models import Word, Search

SEARCH_SUMMARY_SKIPS = (
    'crossword', 'korsord', 'fuck', 'peter', 'motherfucker',
)

def niceboolean(value):
    if isinstance(value, bool):
        return value
    falseness = ('', 'no', 'off', 'false', 'none', '0', 'f')
    return str(value).lower().strip() not in falseness


def uniqify(seq, idfun=None): # Alex Martelli ******* order preserving
    if idfun is None:
        def idfun(x): return x
    seen = set()
    result = []
    for item in seq:
        marker = idfun(item)
        # in old Python versions:
        # if seen.has_key(marker)
        # but in new ones:
        ##if marker in seen: continue
        if marker in seen:
            continue
        seen.add(marker)
        result.append(item)
    return result

class SearchResult(object):
    def __init__(self, word, definition='', by_clue=None):
        self.word = word
        self.definition = definition
        self.by_clue = by_clue



def home(request, json=False, record_search=True):
    # By default we are set to record the search in our stats
    # This can be overwritten by a CGI variable called 'r'
    # E.g. r=0 or r=no
    if request.GET.get('r'):
        record_search = niceboolean(request.GET.get('r'))

    language = request.GET.get('lang', get_language()).lower()

    slots = None

    if request.GET.get('l'):
        try:
            length = int(request.GET.get('l'))
        except ValueError:
            return http.HttpResponseRedirect('/?error=length')
        slots = request.GET.getlist('s')
        # if not type(slots) is list:
        if not isinstance(slots, list):
            return http.HttpResponseRedirect('/?error=slots')

        notletters = request.GET.get('notletters', '').upper()
        notletters = [x.strip() for x in notletters.split(',')
                      if len(x.strip()) == 1 and not x.strip().isdigit()]

        if not len(slots) >= length:
            return http.HttpResponseRedirect('/?error=slots&error=length')

        if not [x for x in slots if x.strip()]:
            # all blank
            return http.HttpResponseRedirect('/?error=slots')

        clues = request.GET.get('clues', '')
        if clues and ' ' in clues and ',' not in clues:
            clues = clues.replace(' ',', ')
        clues = [
            x.strip() for x in clues.split(',')
            if (
                x.strip() and
                x.strip().lower() not in STOPWORDS and
                not x.count(' ')
            )
        ]

        search_results = [] # the final simple list that is sent back

        for clue in clues:
            alternatives = _find_alternative_synonyms(
                clue,
                slots[:length],
                language,
                notletters=notletters,
                request=request
            )
            search_results.extend([
                SearchResult(x, by_clue=clue)
                for x in alternatives
            ])

        # find some alternatives
        search = ''.join([x and x.lower() or ' ' for x in slots[:length]])
        cache_key = '_find_alternatives_%s_%s' % (search, language)
        if notletters:
            cache_key += '__not' + ''.join(notletters)
        cache_key = cache_key.replace(' ','_')
        if re.findall('\s', cache_key):
            raise ValueError(
                'invalid cache_key search=%r, language=%r' % (search, language)
            )

        alternatives = cache.get(cache_key)
        if alternatives is None:
            alternatives = _find_alternatives(
                slots[:length],
                language,
                notletters=notletters
            )
            cache.set(cache_key, alternatives, 60 * 60 * 24)

        alternatives_count = len(alternatives)
        alternatives_truncated = False
        if alternatives_count > 100:
            alternatives = alternatives[:100]
            alternatives_truncated = True

        result = dict(
            length=length,
            search=search,
            word_count=alternatives_count,
            alternatives_truncated=alternatives_truncated,
        )
        already_found = [x.word for x in search_results]
        search_results.extend([
            SearchResult(each.word, definition=each.definition)
            for each in alternatives
            if each.word not in already_found
        ])

        match_points = None
        match_points = []
        if search_results:
            first_word = search_results[0].word
            for i, letter in enumerate(first_word):
                if letter.lower() == search[i]:
                    match_points.append(1)
                else:
                    match_points.append(0)
            result['match_points'] = match_points

        result['words'] = []
        for search_result in search_results:
            v = dict(word=search_result.word)
            if search_result.definition:
                v['definition'] = search_result.definition
            if search_result.by_clue:
                v['by_clue'] = search_result.by_clue
            result['words'].append(v)

        if alternatives_count == 1:
            result['match_text'] = _("1 match found")
        elif alternatives_count:
            if alternatives_truncated:
                result['match_text'] = _(
                    "%(count)s matches found but only showing first 100"
                ) % dict(count=alternatives_count)
            else:
                result['match_text'] = _("%(count)s matches found") % dict(
                    count=alternatives_count
                )
        else:
            result['match_text'] = _("No matches found unfortunately :(")

        found_word = None
        if len(search_results) == 1:
            try:
                found_word = Word.objects.get(
                    word=search_results[0].word,
                    language=language
                )
            except Word.DoesNotExist:
                # this it was probably not from the database but
                # from the wordnet stuff
                found_word = None

        if record_search:

            _record_search(
                search,
                user_agent=request.META.get('HTTP_USER_AGENT',''),
                ip_address=request.META.get('REMOTE_ADDR',''),
                found_word=found_word,
                language=language
            )

        request.session['has_searched'] = True

        if json:
            return http.JsonResponse(result)
            # return _render_json(result)

    else:
        length = ''

    show_example_search = not bool(request.session.get('has_searched'))
    most_recent_search_word = None
    if not show_example_search:
        most_recent_search_word = _get_recent_search_word(request)

    lang = get_language()
    accept_clues = (
        wordnet is not None and lang.lower() in ('en', 'en-gb', 'en-us')
    )

    context = {
        'length': length,
        'slots': slots,
        'accept_clues': accept_clues,
        'show_example_search': show_example_search,
        'most_recent_search_word': most_recent_search_word,
    }
    return render(request, 'search/home.html', context)


def _find_alternatives(slots, language, notletters=[]):
    length = len(slots)

    if length == 1:
        return Word.objects.filter(length=1, word=slots[0], language=language)

    filter_ = dict(length=length, language=language)
    slots = [x and x.lower() or ' ' for x in slots]
    search = ''.join(slots)
    start = ''
    end = ''
    try:
        start = re.findall('^\w+', search)[0]
        if len(start) > 1:
            filter_['first2'] = start[:2].lower()
            if len(start) > 2:
                filter_['word__istartswith'] = start
        else:
            filter_['first1'] = start.lower()
    except IndexError:
        pass

    try:
        end = re.findall('\w+$', search)[0]
        if len(end) > 1:
            filter_['last2'] = end[-2:].lower()
            if len(end) > 2:
                filter_['word__iendswith'] = end
        else:
            filter_['last1'] = end.lower()

    except IndexError:
        pass

    def filter_match(match):
        if end:
            matchable_string = search[len(start):-len(end)]
            found_string = match.word[len(start):-len(end)]
        else:
            matchable_string = search[len(start):]
            found_string = match.word[len(start):]

        assert len(matchable_string) == len(found_string), \
        "matchable_string=%r, found_string=%r" % (matchable_string, found_string)

        for i, each in enumerate(matchable_string):
            if each != ' ' and each != found_string[i]:
                # can't be match
                return False
        return True

    search_base = Word.objects
    limit = 10000
    # if the filter is really vague and the length is high we're going to get
    # too many objects and we need to cut our losses.
    if filter_['length'] > 5:
        if filter_.get('word__istartswith') and filter_.get('word__iendswith'):
            # It's long but has a startswith and an endswith, increase the limit
            limit = 5000
        elif filter_.get('word__istartswith') or filter_.get('word__iendswith'):
            # we're going to get less than above but still many
            limit = 2500
        else:
            limit = 1000

    # if there's neither a start or a end (e.g. '_E_E_A_') it will get all words

kl/search/templates/search/about-crosstips.html
{% extends base_template %}
{% load i18n %}

{% block title %}{% trans "About Crosstips" %}{% endblock %}

{% block main %}
<h3>{% trans "About Crosstips" %}</h3>

<p>Crosstips helps you when you get stuck solving crosswords. It's not
  cheating if you really got stuck simply don't know the word
  you're looking for. </p>

<p>This website was done over Christmas 2008 by
  <a href="https://www.peterbe.com/">Peter Bengtsson</a> in
  <a href="https://www.djangoproject.com/">Django</a>.
  The words come from the Open Source Ubuntu package
  <a href="http://packages.ubuntu.com/intrepid/wordlist">wordlist</a>.</p>

<p style="font-size:80%;padding-top:60px">
<a href="/">&lt;&lt; {% trans "Go back to home page" %}</a>
</p>

{% endblock %}

kl/search/templates/search/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="{{ request.LANGUAGE_CODE }}">
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}

<head>
  <meta http-equiv="Content-Language" content="{{ LANGUAGE_CODE }}">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="description" content="{% block meta_content %}{% trans "helps you solve your crossword puzzles" %}{% endblock %}">
  <meta name="keywords" content="{% block meta_keywords %}{% trans "crosstip, crosstips, crossword, crosswords, puzzle, crossword puzzles" %}{% endblock %}">
  <title>{% block title %}{% trans "Crosstips" %} - {% trans "crossword solver, fast and simple" %}{% endblock %}</title>

  <link rel="shortcut icon" href="{% static "search/images/favicon.ico" %}">
  <link rel="stylesheet" href="{% static "search/css/boilerplate.css" %}" type="text/css" media="screen" charset="utf-8">
  <link rel="stylesheet" href="{% static "search/css/core.css" %}" type="text/css" media="screen" charset="utf-8">

{% block extracss %}
{% endblock %}

{% if GOOGLE_ANALYTICS %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-94373-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script');
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
        'http://www') + '.google-analytics.com/ga.js';
    ga.setAttribute('async', 'true');
    document.documentElement.firstChild.appendChild(ga);
  })();
</script>
{% endif %}

</head>

<body id="profile_6" class=" user_book_list" {% block extrabody %}{% endblock %}>
  <div id="page">

    <div id="body">


          {% block reader_sidebar_outer %}
          <div class="sidebar reader_sidebar">
          {% block reader_sidebar %}
          <form action="/i18n/setlang/" method="post">
            <ul>
              {% for language_option in language_options %}
                <li {% if language_option.on %}class="on"{% endif %}><a
                {% if language_option.title %}title="{{ language_option.title }}"{% endif %}
                href="{{ language_option.href }}">{{ language_option.label }}</a></li>
              {% endfor %}
            </ul>

          </form>

          {% endblock %} {# reader_sidebar #}
          </div>
          {% endblock %} {# reader_sidebar_outer #}


        <div class="content_wrapper">
          <div class="content">



            <div class="content_title">
	        <h3 style="float:right">{% block pagetitletagline %}{% trans "crossword solver, fast and simple" %}{% endblock %}</h3>
                <h2>{% block pagetitle %}{% trans "Crosstips" %}{% endblock %}</h2>
            </div>

{% block main %}
{% endblock %}


          </div>
  {% block content_sidebar_outer %}
          <div class="content_sidebar">

  {% block content_sidebar %}
  <h3>{% trans "Statistics" %}</h3>
  <ul>
    <li><a>{% trans "Searches today" %} <em>{{ no_searches_today }}</em></a></li>
    <li><a>{% trans "Searches yesterday" %} <em>{{ no_searches_yesterday }}</em></a></li>
    <li><a>{% trans "Searches this week" %} <em>{{ no_searches_this_week }}</em></a></li>
    <li><a>{% trans "Searches this month" %} <em>{{ no_searches_this_month }}</em></a></li>
    <li><a>{% trans "Searches this year" %} <em>{{ no_searches_this_year }}</em></a></li>
    <li><a>{% trans "Total number of words" %} <em>{{ no_total_words }}</em></a></li>
  </ul>
  <br><br>
  <br><br>
  <br>

  {% endblock %}

          </div>
  {% endblock %}
        </div>

    </div>


    <div id="footer">

      <p class="copyright">
        <small>
          <a href="/">{% trans "Crosstips" %} &copy; 2009-2017</a>
          <a href="https://www.peterbe.com/">Peterbe.com</a>
          <a href="https://songsear.ch">Song Search</a>
          {% ifequal LANGUAGE_CODE "sv" %}
          <a href="/om/krysstips/">Om Krysstips</a>
          <a href="/om/dsso/">Om DSSO</a>
          {% else %}
          <a href="/about/crosstips/">About Crosstips</a>
          {% endifequal %}
          {% comment %}<a href="/statistics/calendar/">{% trans "Calendar" %}</a>{% endcomment %}
          {% comment %}<a href="/statistics/graph/">{% trans "Graph" %}</a>{% endcomment %}
          {% if searches_summary_link %}
          <a href="{{ searches_summary_link }}">{% trans "Searches summary" %}</a>
          {% endif %}
        </small>
      </p>
    </div>


  </div>

<script type="text/javascript" src="{% static "search/js/jquery-1.3.2.min.js" %}"></script>
<script type="text/javascript" src="{% static "search/js/jquery.site.js" %}"></script>
{% block extrajs %}{% endblock %}

</body>
</html>

kl/search/templates/search/home.html
{% extends base_template %}
{% load i18n %}
{% load static %}

{% block extracss %}
<style type="text/css">
#allslots {
  padding:0; margin:0;
}
div.sugg {
  line-height:150%;
}
div.sugg span {
  font-family:"courier new",courier;
  padding:0px 5px;
  font-size:18px;
  border:1px solid #ccc;
}
div.sugg abbr {
  padding-left:10px;
  font-size:80%;
}

span.match {
  font-weight:bold;
}
div.error {
  font-weight:bold;
  color:red;
}
em.definition { font-size:80%; padding-left:10px; color:#666666; }
a.clear-search { font-size:80%;}
input#id_length, #allslots input { font-weight:bold; font-size:120% }
p.recently-found { font-size:80%; }
</style>
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{% static "search/js/jquery.form.js" %}"></script>
<script type="text/javascript" src="{% static "search/js/solve.js" %}"></script>
{% endblock %}


{% block main %}

<form action="./" id="solutions">
<p>
  <label for="id_length">{% trans "Number of letters" %}:</label>
  <input id="id_length" type="number" name="l" size="2" maxlength="2" autocomplete="off" value="{{ length }}"><br>

  <label>{% trans "Slots" %}:</label>
  <span id="allslots">
  {% for letter in slots %}<input name="s" value="{{ letter }}" size="1" maxlength="1">{% endfor %}
  </span>
  <br>
  {% if accept_clues %}
    <span id="clues" style="display:none">
    <label>{% trans "Clue(s):" %}</label>
    <input name="clues" value="" size="12">
      <small>(word clues separated by a comma)</small>
    </span><br>
  {% endif %}
  {% if accept_clues %}
    <span id="notletters" style="display:none">
    <label>{% trans "Letters it is <em>not</em>:" %}</label>
    <input name="notletters" value="" size="12">
      <small>(useful when playing hangman)</small>
    </span><br>
  {% endif %}


  <input type="submit" value="{% trans "Search" %}">
  <img id="loading" style="display:none" src="{% static "search/images/loading-bar.gif" %}" alt="{% trans "Loading" %}" width="150" height="15">
  <a href="./" id="clear-search" style="display:none">{% trans "clear search" %}</a>
</p>
</form>

<div id="error__no_s" class="error" style="display:none">
{% trans "No letters all?" %}
</div>
<div id="error__ajax" class="error" style="display:none">
{% trans "Sorry. Unable to do a search right now. Please try again a bit later." %}<br>
<code class="response"></code>
</div>


<div id="matches"></div>
<div id="alternatives"></div>

{% if show_example_search %}
<div id="for-example">
<p>{% blocktrans %}
Stumped? Crosstips <strong>helps</strong> you <strong>solve</strong> your <strong>crossword puzzles</strong>.
Enter the length of the word and fill in the known letters.
{% endblocktrans %}</p>

{% ifequal request.LANGUAGE_CODE "sv" %}
<p>Till exempel, <a href="/" rel="nofollow" onclick="run_example(7, ['K','O','','','O','','D']);return false">vilket ord b&ouml;rjar p&auml; KO, femte bokstaven O och slutar p&auml; bokstaven D?</a>
{% else %}
<p>For example, <a href="/" rel="nofollow" onclick="run_example(9, ['C','','O','','','','','R','D']);return false">what's
a 9 letter word that starts with C, third letter O and ends with RD?</a>
{% endifequal %}
</div>

{% else %}

{% endif %}

<p>&nbsp;</p>

{% comment %}
<p>
<strong>{% trans "See also:" %}</strong>
<a href="/simple/">{% trans "simple inferface" %}</a>,
<a href="/iphone/">{% trans "iPhone interface" %}</a>,
<a href="/word-whomp/">{% trans "Word Whomp" %}</a>
</p>
{% endcomment %}

{% if most_recent_search_word %}
  <p>&nbsp;</p>
  <p class="recently-found">
  <strong>{% trans "By the way..." %}</strong><br>
  {% trans "Crosstips recently helped someone find the word:" %}
  <a href="{{ searches_summary_link }}#{{ most_recent_search_word.word }}">{{ most_recent_search_word.word }}</a>
  {% if most_recent_search_word.definition %}
  <br>({% trans "which means" %} <em>{{ most_recent_search_word.definition }}</em>)
  {% endif %}
  </p>
{% endif %}


{% endblock %}

kl/search/templates/search/searches_summary.html
{% extends base_template %}
{% load i18n %}

{% block title %}{% trans "Searches summary in" %} {{ month }} {{ year }} - {% trans "Crosstips" %}{% endblock %}

{% block extrajs %}
<script type="text/javascript">

function __focus_li(li) {
     li.fadeOut(200, function() {
        li.addClass('focused');
        li.fadeIn("slow");
      });
}

$(function() {
  if (document.location.hash) {
    var a = $('a[name="' +document.location.hash.substring(1, document.location.hash.length) +'"]');
    if (a.size()) {
      __focus_li(a.parent('li'));
    }
  }
  $('li', 'ul.words').click(function() {
    $('li.focused').removeClass('focused');
    if ($('a', this).attr('name').toLowerCase() == document.location.hash.substring(1, document.location.hash.length).toLowerCase()) {
      //document.location.hash = '';
    } else {
      __focus_li($(this));
      document.location.hash = $('a', this).attr('name');
    }
  });
});
</script>
{% endblock %}

{% block extracss %}
<style type="text/css">
li.focused { background-color:#efefef; }
ul.words em { padding-left:10px; font-size:70%; color:#666666; line-height:1px;}
ul.words a { padding-left:10px; font-size:70%; }
</style>
{% endblock %}

{% block meta_content %}{% trans "Searches summary in" %} {{ month }} {{ year }}{% endblock %}
{% block meta_keywords %}{% for word in all_words_plain %}{{ word }},{% endfor %}{% endblock %}

{% block main %}
<h3>{% trans "Searches summary in" %} {{ month }} {{ year }}</h3>

<p>Crosstips helped to find the following words this month:</p>
{% for language, words in found_words_repeats.items %}
  {% if words %}
    <p><strong>{{ language }}</strong></p>
    <ul class="words">
    {% for word in words %}
      <li class="{{ language }} {% if not word.definitions %}definitionless{% endif %}">{{ word.word }}
      <a name="{{ word.word }}"></a>

        {% if word.definitions %}
        <br/>

          {% for definition in word.definitions %}
          <em>{{ definition }}</em>{% if not forloop.last %};<br/>{% endif %}
          {% endfor %}
        {% endif %}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
{% endfor %}
<br/>

<br/>
<p>These are words that are found when someone searches with exactly so many clues
that only one single alternative is found.
</p>

<p style="font-size:80%;padding-top:60px">

{% if previous_month_link %}
<a href="{{ previous_month_link }}">&lt;&lt;&lt; {% trans "Previous month" %}</a>
{% endif %}
&nbsp;
{% if next_month_link %}
<a href="{{ next_month_link }}">{% trans "Next month" %} &gt;&gt;&gt;</a>
<br/>
{% endif %}
<br/>
<a href="/">&lt;&lt; {% trans "Go back to home page" %}</a>
</p>

{% endblock %}